github:
  description: "Apache Sling Adapter Annotations Integration Tests (deprecated)"
  homepage: "https://sling.apache.org/"
  labels:
    - sling
    - java
    - annotations
    - adapters
    - deprecated
