github:
  description: "Apache Sling Adapter Annotations Integration Tests (deprecated)"
  homepage: "https://sling.apache.org/"
  labels:
  - "sling"
  - "java"
  - "annotations"
  - "adapters"
  - "deprecated"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
